version: '3.2'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data  
  auth-service:
    build:
      context: ./auth-service  # Обрати внимание на путь
      dockerfile: Dockerfile
    container_name: auth-service-container
    ports:
      - "8081:8081"


  api-gateway:
    build:
      context: ./api-gateway  # Убедись, что путь верный
      dockerfile: Dockerfile
    container_name: api-gateway-container
    ports:
      - "8080:8080"

  


volumes:
  db_data:
    driver: local
networks:
  kafka-network:
    driver: bridge
